version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - build-artifacts:/app/dist

  server:
    image: nginx:latest
    depends_on:
      - builder
    volumes:
      - build-artifacts:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  build-artifacts:
